name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG with custom style
        uses: Platane/snk@v3
        with:
          github_user_name: akash7i
          outputs: |
            dist/snake.svg
          color_snake: "#00ffff"               # Neon cyan
          color_dots: "#f0f0f0,#ffffff"        # Light grey + white dots
          background_color: "#00000000"        # Transparent

      - name: Show output folder
        run: ls -R dist

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
