name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs at midnight every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Akash7i
          outputs: |
            dist/github-contribution-grid-snake.svg
          # 💡 Customize the appearance
          color_snake: '#00FF99'
          color_dots: '#FFD700,#FF4500,#1E90FF,#32CD32,#9400D3'
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show output folder
        run: ls -R dist

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
